### ISSUE TITLE
JAX v0.4.37 - ImportError: cannot import name 'process_env_traces' from 'jax._src.custom_derivatives' 

### ISSUE THREAD

**Issue by adam-hartshorne** [jamielohoff/graphax#3]
It appears your library is not compatible with JAX v0.4.37 (the following code works fine on v0.4.35)

```
def simple_func(x, y):
    x = jnp.sin(x)
    var = jnp.var(x)
    return y / var

x = jnp.arange(0, 6) * 0.1
y = jnp.ones((6,))
print(jax.make_jaxpr(jacve(simple_func, order="fwd", argnums=(0, 1)))(x, y))
```

    from graphax import jacve, filter_jacve, tree_allclose
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/graphax/__init__.py", line 2, in <module>
    from .core import jacve, tree_allclose
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/graphax/core.py", line 15, in <module>
    from .primitives import elemental_rules
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/graphax/primitives.py", line 14, in <module>
    from .sparse.tensor import (SparseTensor, DenseDimension, SparseDimension, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/graphax/sparse/__init__.py", line 1, in <module>
    from .custom_derivatives import custom_elemental
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/graphax/sparse/custom_derivatives.py", line 14, in <module>
    from jax._src.custom_derivatives import process_env_traces
ImportError: cannot import name 'process_env_traces' from 'jax._src.custom_derivatives' (/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/jax/_src/custom_derivatives.py)

**Comment by jamielohoff** [comment]
Thanks for this pointer. The problem here is that the `process_env_traces` function was renamed in the latest update to the JAX core library. This will attempt to fix that immediately.

**Comment by jamielohoff** [comment]
This one should be fixed in the latest version of the code.
